config/routes.rb
Rails.application.routes.draw do
	
  devise_for :users
  resources :restaurants do
  	resources :reviews, except: [:show, :index]
	end
	
  root 'restaurants#index'

  get 'pages/about'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  
  mount_uploader :image, ImageUploader
  has_many :reviews
  validates :name, :address, :phone, :website, :image, presence: true
  validates :phone, format: { with: /\A\(\d{3}\) \d{3} \d{3}\z/,
    message: "must be in the format of: (091) 123 123" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
    message: "must start with http:// or https//" }        
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  validates :rating, :comment, presence: true
  validates :rating, numericality: {
  	only_integer: true,
  	greater_than_or_equal_to: 1,
  	less_than_or_equal_to: 5,
  	message: "Can only be a whole number between 1 and 5"
  }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews, dependent: :destroy
  
  validates :first_name, :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])

  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show]


  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @reviews = Review.where(restaurant_id: @restaurant.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
    
    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: 'Sorry, only admin has permission'
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_restaurant
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.restaurant_id = @restaurant.id
    
    respond_to do |format|
      if @review.save
        format.html { redirect_to @restaurant, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_path(@restaurant), notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
    
    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: 'Sorry, this review belongs to someone else'
      end
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
def devise_error_messages!
  return "" if resource.errors.empty?
  
  messages = resource.errors.full_messages.map { |msg| content_tag(:p, msg) }.join
  sentence = I18n.t("errors.messages.not_saved",
  :count => resource.errors.count,
  :resource => resource.class.model_name.human.downcase)
  
html = <<-HTML

<div class="alert alert-danger alert-dismissable">
<button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
<span class="sr-only">Close</span></button>
<h4>#{sentence}</h4>

#{messages}

</div>

HTML

html.html_safe

end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_bootstrap.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<p>&copy; 2018 Jacqueline Walsh</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg">
  <%= link_to "ReviewDemo", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li><%= link_to "About", pages_about_path, class:"nav-link" %></li>
        <li><%= link_to "Contact", pages_contact_path, class:"nav-link" %></li>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>      
    </ul>
    <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %></li> 
          <li><%= link_to "Sign Out", destroy_user_session_path, class:"nav-link", method: :delete %></li>
        <% else %>       
          <li><%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class:"nav-link" %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Review Demo</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navbar' %>
<div class="container-fluid">
  
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name=="notice" ? "success" : "danger" %> alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span><span 
        class="sr-only">Close</span></button>
      <%= content_tag :div, msg, :id => "flash_#{name}"%>
    </div>
  <% end %>
<% end %>

  <%= yield %>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Review Demo</h1>
<p>This is one of the sample applications for <%= link_to "Simply Web Design", "http://www.simplyweb.ie" %>, a platform that teaches people to build awsome 
custom websites with the ruby on rails programming language</p>

app/views/pages/contact.html.erb
<h1>We would love to here from you!</h1>
<p>Contact us at jacqueline@simplyweb.ie</p>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => {multipart: true}) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alter-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control", placeholder:"Joe Blogs"%>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class:"form-control", placeholder:"12 Anywhere Street, Loughrea, Co Galway" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control", placeholder:"(091) 123 123" %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class:"form-control", placeholder:"http://websitename.com" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"form-control" %>
  </div>  
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<div class="jumbotron">
  <h2>Review Demo is the best way to find reviews on local restaurants</h2>
  <h3>Explore the favourite diners, pastery shops in your community<br/>
  Leave reviews and ratings for your fellow foodies</h3>
  </div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website %></td>

        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class:"btn btn-link" %></td>
          <td><%= link_to 'Destroy', restaurant, class:"btn btn-link", method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_signed_in? && current_user.admin? %>
  <%= link_to 'New Restaurant', new_restaurant_path, class:"btn btn-link" %>
<% end %>
<%= image_tag 'footer_logo.jpg', class:"restaurant_img" %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link"  %>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-md-4">  
    <p></p>
      <%= image_tag @restaurant.image_url %>
    </p>  
    <p>
      <h2>
      <%= @restaurant.name %>
      </h2>
    </p>

      <div class="star-rating" data-score= <%= @avg_rating %> ></div>
        <p><%= "#{@reviews.length} reviews" %></p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @restaurant.phone %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= link_to @restaurant.website, @restaurant.website %>
    </p>

    <%= link_to 'Write a Review', new_restaurant_review_path(@restaurant), class:"btn btn-primary" %>
    <p><br/>
      <iframe id="map" src="//www.google.com/maps/embed/v1/place?q=<%= @restaurant.address.parameterize %>
      &zoom=17 &key=AIzaSyAo-s0skUnttfDaF1bONOTtdslnvIUbBvc">
      </iframe>
    </p>
    <p>
      <%= link_to 'Edit', edit_restaurant_path(@restaurant), class:"btn btn-link" %> |
      <%= link_to 'Back', restaurants_path, class:"btn btn-link" %>
    </p>

  </div>

  <div class="col-md-8">
    <% if @reviews.blank? %>
      <h3>No reviews yet! Be the first to write one.</h3>
    <% else %>

    <table class="table">
      <tbody>

        <% @reviews.each do | review | %>  

        <tr>
          <td>
            <h4><%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}."%></h4>
            <p><%= review.created_at.strftime("%d/%m/%y") %></p>
          </td>

          <td>
            <div class="star-rating" data-score= <%= review.rating %> ></div>
            <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe %></p>   

            <% if user_signed_in? %>     
              <% if (review.user == current_user) || (current_user.admin?) %>    
                <%= link_to "Edit", edit_restaurant_review_path(@restaurant, review), class:"btn btn-link"  %> |
                <%= link_to "Delete", restaurant_review_path(@restaurant, review), class:"btn btn-link" , method: :delete %>
              <% end %>
            <% end %>
          </td>
        </tr>

      <% end %>

      </tbody>
    </table>
    <% end %>
  </div>  
</div>

<script>
  $('.star-rating').raty({
    path: '/assets/stars',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alter-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <div id="star-rating"></div>
  </p>
  <div class="form-group">
    <%= f.label :comment %>
    <%= f.text_area :comment, class:"form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class:"btn btn-primary"%>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/stars', 
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', restaurant_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', restaurant_path(@restaurant) %>